# Generated by Django 4.2.3 on 2024-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=512)),
                ('format', models.CharField(max_length=256)),
                ('size', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
