# Generated by Django 4.2.3 on 2024-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_backup',
            field=models.DateTimeField(null=True),
        ),
    ]
