# Generated by Django 4.2.3 on 2023-08-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_description_video_file_name_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
