# Generated by Django 4.2.3 on 2023-08-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_file_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keywords',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
