# Generated by Django 4.2.3 on 2024-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_video_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solare Ranked'), (1, 'Solare Practice'), (2, 'Backup'), (3, 'Upload')], default=0),
        ),
    ]
