# Generated by Django 4.2.3 on 2024-01-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Processando'), (2, 'Processamento falhou'), (3, 'Processamento concluido'), (4, 'Enviando'), (6, 'Sucesso'), (7, 'Falhou'), (8, 'Finalizado')], default=0),
        ),
    ]
