# Generated by Django 4.2.3 on 2024-09-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_file_last_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('mountpoint', models.CharField(max_length=256)),
                ('fstype', models.CharField(max_length=16)),
                ('opts', models.CharField(max_length=512)),
            ],
        ),
    ]
