# Generated by Django 4.2.3 on 2025-03-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_disk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('observation', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
