# Generated by Django 4.2.3 on 2023-08-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
