# Generated by Django 4.2.3 on 2023-08-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
