# Generated by Django 4.2.3 on 2023-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(blank=True, max_length=12, null=True)),
                ('upload_status', models.CharField(blank=True, max_length=32, null=True)),
                ('privacy_status', models.CharField(blank=True, max_length=32, null=True)),
                ('view_count', models.CharField(blank=True, max_length=32, null=True)),
                ('like_count', models.CharField(blank=True, max_length=32, null=True)),
                ('dislike_count', models.CharField(blank=True, max_length=32, null=True)),
                ('comment_count', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
